import React, { useEffect, useState } from 'react';
import { ScatterChart, Scatter, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, Legend } from 'recharts';
import { Info } from 'lucide-react'; // Optional: for the metadata tooltip

const COLORS = {
  'Justified Optimism': '#4ade80', // Green
  'Bull Trap': '#f87171',          // Red
  'Justified Fear': '#ef4444',     // Dark Red
  'Bear Trap': '#60a5fa',          // Blue
  'Noise': '#334155'               // Slate-700
};

const CustomTooltip = ({ active, payload }) => {
  if (active && payload && payload.length) {
    const data = payload[0].payload;
    return (
      <div className="bg-slate-900 border border-slate-700 p-3 rounded shadow-xl text-xs max-w-xs z-50">
        <div className="flex justify-between items-center mb-2">
            <span className="font-bold text-white bg-slate-800 px-2 py-0.5 rounded">{data.ticker}</span>
            <span className="text-slate-400 text-[10px]">
              {new Date(data.published_at).toLocaleDateString()}
            </span>
        </div>
        <p className="text-slate-200 italic mb-2 leading-tight">"{data.title}"</p>
        <div className="flex justify-between border-t border-slate-700 pt-2">
            <span style={{color: COLORS[data.label] || '#fff'}}>{data.label}</span>
            <span className={data.sentiment > 0 ? "text-green-400" : "text-red-400"}>
                Sent: {data.sentiment?.toFixed(2)}
            </span>
        </div>
      </div>
    );
  }
  return null;
};

export default function MarketPsychologyMap() {
  const [chartData, setChartData] = useState([]);
  const [meta, setMeta] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // 1. Fetch the JSON generated by your Airflow DAG
    fetch('https://cdn.catincloud.io/data/market_psychology_map.json')
      .then(res => res.json())
      .then(payload => {
        // 2. Unpack the nested structure
        setChartData(payload.data || []);
        setMeta(payload.meta);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load map:", err);
        setLoading(false);
      });
  }, []);

  if (loading) return <div className="w-full h-96 bg-slate-950 rounded-xl animate-pulse" />;

  return (
    <div className="w-full h-[600px] bg-slate-950 rounded-xl border border-slate-800 p-4 relative overflow-hidden flex flex-col">
      
      {/* Header with Metadata */}
      <div className="flex justify-between items-start mb-2 px-2">
        <div>
          <h2 className="text-lg font-bold text-white">Market Psychology Map</h2>
          <p className="text-xs text-slate-400">
            Clustering {chartData.length} Articles • Last Updated: {meta?.generated_at ? new Date(meta.generated_at).toLocaleString() : 'Just now'}
          </p>
        </div>
        {/* Optional: Inspector Trigger */}
        <div className="group relative cursor-help">
            <Info size={16} className="text-slate-500 hover:text-slate-300" />
            <div className="absolute right-0 w-64 bg-slate-900 border border-slate-700 p-2 rounded text-[10px] text-slate-400 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-10">
                {meta?.inspector?.description}
            </div>
        </div>
      </div>
      
      {/* The Chart */}
      <div className="flex-1 w-full min-h-0">
        <ResponsiveContainer width="100%" height="100%">
          <ScatterChart margin={{ top: 20, right: 20, bottom: 20, left: 20 }}>
            {/* Hide Axes for map-like appearance */}
            <XAxis type="number" dataKey="x" hide domain={['auto', 'auto']} />
            <YAxis type="number" dataKey="y" hide domain={['auto', 'auto']} />
            
            <Tooltip content={<CustomTooltip />} cursor={{ strokeDasharray: '3 3', stroke: '#555' }} />
            
            <Legend 
              verticalAlign="bottom" 
              height={36} 
              iconType="circle"
              wrapperStyle={{ fontSize: '12px', paddingTop: '10px' }}
            />
            
            <Scatter name="Clusters" data={chartData} fill="#8884d8">
              {chartData.map((entry, index) => (
                <Cell 
                  key={`cell-${index}`} 
                  fill={COLORS[entry.label] || COLORS['Noise']} 
                  // Visual Logic: Fade out noise, pop the signals
                  opacity={entry.label === 'Noise' ? 0.3 : 0.8}
                  // Size Logic: Impact dictates size. 
                  r={entry.label === 'Noise' ? 2 : Math.min(15, 4 + (Math.abs(entry.impact || 0) * 800))} 
                />
              ))}
            </Scatter>
          </ScatterChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
